### ISSUE TITLE
how to install the mdpsim module and ssipp module which appear in the supervised.py?

### ISSUE THREAD

**Issue by a540611121** [qxcv/asnets#1]
I download the code and try to run it but something go wrong.
The error is ModuleNotFoundError: No module name 'mdpsim'.
I check the code and find it appear in the line 189 and line 190 ,can anyone tell me how to solve it ?

**Comment by qxcv** [comment]
mdpsim and ssipp are custom modules. If you follow the [installation instructions in the README](https://github.com/qxcv/asnets/tree/master/deepfpg#installation) then they should get installed automatically. The key line is `pip install --process-dependency-links -r requirements.txt`, which will install everything in [`requirements.txt`](https://github.com/qxcv/asnets/blob/master/deepfpg/requirements.txt), including these two dependencies:

```
# my mdpsim bindings
git+https://gitlab.cecs.anu.edu.au/u5568237/mdpsim.git
# my ssipp bindings
git+https://gitlab.com/qxcv/ssipp.git
```

If you want to install them manually you can instead do `pip install 'git+https://gitlab.com/qxcv/ssipp.git' 'git+https://gitlab.cecs.anu.edu.au/u5568237/mdpsim.git'`.
